name: Python package


on: push
jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: '3.10'  # Или другая версия

    - name: Install dependencies

      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip

        pip install selenium webdriver-manager

    - name: Run the script

      run: python проход.py  # Укажите имя вашего скрипта
